# Generated by Django 4.2.13 on 2026-06-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ar_file',
            new_name='android_ar_file',
        ),
        migrations.AddField(
            model_name='product',
            name='ios_ar_file',
            field=models.FileField(blank=True, null=True, upload_to='product/ar/files/'),
        ),
        migrations.AddField(
            model_name='product',
            name='web_ar_file',
            field=models.FileField(blank=True, null=True, upload_to='product/ar/files/'),
        ),
    ]
