# Generated by Django 4.2.13 on 2026-06-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_moderatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onesignal_player_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onesignal_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
