# Generated by Django 4.2.13 on 2026-05-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprofile',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
