# Generated by Django 5.2 on 2026-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_onesignal_player_id_user_onesignal_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=20),
        ),
    ]
