# Generated by Django 4.2.13 on 2026-05-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_supplierprofile_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
