# Generated by Django 4.2.13 on 2026-06-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='body',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data',
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Store order_id, chat_id, supplier_id etc.', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_event',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('supplier_approved', 'Supplier Approved'), ('return_update', 'Return Update'), ('promo', 'Promotion'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('push', 'Push'), ('in_app', 'In pp'), ('email', 'Email')], default='push', max_length=20),
        ),
    ]
